"use strict";
exports.__esModule = true;
var arma_1 = require("./arma");
var metralhadora_1 = require("./metralhadora");
var pistola = new arma_1.arma(10, 10);
pistola.atirar(1);
pistola.informarBalas();
var ak = new metralhadora_1.metralhadora(10, 10);
ak.atirar();
ak.informarBalas();
